# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Docs

# on: workflow_dispatch

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  publish:
  # The type of runner that the job will run on
    strategy:
      matrix:
#         os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        # python-version: ["3.7", "3.8", "3.9"]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

     #----------------------------------------------
     #-------  install & configure Python  ---------
     #---------------------------------------------- 
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
              
      #----------------------------------------------
      #    deploy documentation
      #----------------------------------------------  
      - name: Create .nojekyll file.
        run: | 
          > .nojekyll
        
      - name: Deploy documentation to gh-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/_build/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
